/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controler.Controler;
import domen.AbstractObject;
import domen.Kompanija;
import domen.Student;
import domen.Zaposleni;
import exception.BrisanjeKompanijeException;
import exception.BrisanjeStudentaException;
import exception.UcitavanjeKompanijaException;
import exception.UcitavanjeStudenataException;
import java.awt.HeadlessException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.KompanijaTableModel;
import model.StudentTableModel;

/**
 *
 * @author FILIP
 */
public class MainForm extends javax.swing.JFrame {
    
    private Zaposleni zaposleni;
    public StudentTableModel studentModel;
    public KompanijaTableModel kompanijaModel;
    
    private List<AbstractObject> studenti;
    private List<AbstractObject> kompanije;    
    /**
     * Creates new form MainFrom
     * @param zaposleni
     */
    
    
    public MainForm(Zaposleni zaposleni) throws HeadlessException {
        this();
        this.zaposleni = zaposleni;
    }

    public MainForm() {
        initComponents();
        srediStudentTabelu();
        srediKompanijaTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudenti = new javax.swing.JTable();
        jTextFieldKriterijumStudent = new javax.swing.JTextField();
        jButtonPretraziStudenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKriterijumKompanija = new javax.swing.JTextField();
        jButtonPronadjiKompaniju = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableKompanija = new javax.swing.JTable();
        jButtonIzmijeniStudenta = new javax.swing.JButton();
        jButtonObrisiStudenta = new javax.swing.JButton();
        jButtonDodajStudentaUPraksu = new javax.swing.JButton();
        jButtonDodajKompanijuUPraksu = new javax.swing.JButton();
        jButtonImijeniKompaniju = new javax.swing.JButton();
        jButtonObrisiKompaniju = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evidencija praksi");

        jTableStudenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStudenti);

        jButtonPretraziStudenta.setText("Pretrazi");
        jButtonPretraziStudenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziStudentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Unesite kljucnu rijec za pretragu studenta:");

        jLabel2.setText("Unesite kljucnu rijec za pretragu kompanije:");

        jButtonPronadjiKompaniju.setText("Pretrazi");
        jButtonPronadjiKompaniju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPronadjiKompanijuActionPerformed(evt);
            }
        });

        jTableKompanija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableKompanija);

        jButtonIzmijeniStudenta.setText("Izmijeni");
        jButtonIzmijeniStudenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmijeniStudentaActionPerformed(evt);
            }
        });

        jButtonObrisiStudenta.setText("Obrisi");
        jButtonObrisiStudenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiStudentaActionPerformed(evt);
            }
        });

        jButtonDodajStudentaUPraksu.setText("Dodaj u praksu");

        jButtonDodajKompanijuUPraksu.setText("Dodaj u praksu");

        jButtonImijeniKompaniju.setText("Izmijeni");
        jButtonImijeniKompaniju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImijeniKompanijuActionPerformed(evt);
            }
        });

        jButtonObrisiKompaniju.setText("Obrisi");
        jButtonObrisiKompaniju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiKompanijuActionPerformed(evt);
            }
        });

        jMenuBar1.setMinimumSize(new java.awt.Dimension(1, 1));
        jMenuBar1.setName(""); // NOI18N

        jMenu1.setText(" Studenti");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Unesi novog studenta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kompanije");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Dodaj kompaniju");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonObrisiStudenta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonIzmijeniStudenta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonDodajStudentaUPraksu))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextFieldKriterijumStudent)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonPretraziStudenta))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonObrisiKompaniju)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonImijeniKompaniju)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonDodajKompanijuUPraksu))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextFieldKriterijumKompanija, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPronadjiKompaniju)))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKriterijumStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretraziStudenta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIzmijeniStudenta)
                    .addComponent(jButtonObrisiStudenta)
                    .addComponent(jButtonDodajStudentaUPraksu))
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKriterijumKompanija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPronadjiKompaniju))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodajKompanijuUPraksu)
                    .addComponent(jButtonImijeniKompaniju)
                    .addComponent(jButtonObrisiKompaniju))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        PodaciStudentForm psf = new PodaciStudentForm(this);
        psf.setVisible(true);
        psf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        PodaciKompanijaForm pkf = new PodaciKompanijaForm(this);
        pkf.setVisible(true);
        pkf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonPretraziStudentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziStudentaActionPerformed
        // TODO add your handling code here:
        String kljucnaRijec = jTextFieldKriterijumStudent.getText();
        List<AbstractObject> pronadjeniStudenti = new ArrayList<>();
        for (AbstractObject student : studenti) {
            if(student instanceof Student) {
                if(student.toString().toLowerCase().indexOf(kljucnaRijec.toLowerCase()) != -1) {
                pronadjeniStudenti.add((Student)student);
            }
            }
            
        }
        studentModel.setStudenti(pronadjeniStudenti);
        studentModel.fireTableDataChanged();
    }//GEN-LAST:event_jButtonPretraziStudentaActionPerformed

    private void jButtonPronadjiKompanijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPronadjiKompanijuActionPerformed
        // TODO add your handling code here:
        String kljucnaRijec = jTextFieldKriterijumKompanija.getText();
        List<AbstractObject> pronadjeneKompanije = new ArrayList<>();
        for (AbstractObject kompanija : kompanije) {
            if(kompanija instanceof Kompanija) {
                if(kompanija.toString().toLowerCase().indexOf(kljucnaRijec.toLowerCase()) != -1) {
                    pronadjeneKompanije.add((Kompanija)kompanija);
                }
            }
            
        }
        kompanijaModel.setKompanije(pronadjeneKompanije);
        kompanijaModel.fireTableDataChanged();
    }//GEN-LAST:event_jButtonPronadjiKompanijuActionPerformed

    private void jButtonObrisiStudentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiStudentaActionPerformed
        try {
            // TODO add your handling code here:
            Student student = (Student) studentModel.getStudenti().get(jTableStudenti.getSelectedRow());
            Controler.getInstance().obrisiStudenta(student);
//            ako ne baci exception nastavalja se normalno
            studentModel.getStudenti().remove(student);
            studentModel.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Uspjesno brisanje studenta sa podacima " + student);
            
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BrisanjeStudentaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonObrisiStudentaActionPerformed

    private void jButtonIzmijeniStudentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmijeniStudentaActionPerformed
        // TODO add your handling code here:
        Student student = (Student) studentModel.getStudenti().get(jTableStudenti.getSelectedRow());
        JOptionPane.showMessageDialog(this, student.getStudentID());
        PodaciStudentForm psf = new PodaciStudentForm(student, this);
        
        psf.setVisible(true);
        psf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        
    }//GEN-LAST:event_jButtonIzmijeniStudentaActionPerformed

    private void jButtonObrisiKompanijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiKompanijuActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Kompanija kompanija = (Kompanija) kompanijaModel.getKompanije().get(jTableKompanija.getSelectedRow());
            Controler.getInstance().obrisiKompaniju(kompanija);
//            ako ne baci exception nastavalja se normalno
            kompanijaModel.getKompanije().remove(kompanija);
            kompanijaModel.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Uspjesno brisanje kompanije sa podacima " + kompanija);
            
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BrisanjeKompanijeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonObrisiKompanijuActionPerformed

    private void jButtonImijeniKompanijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImijeniKompanijuActionPerformed
        // TODO add your handling code here:
        Kompanija kompanija = (Kompanija) kompanijaModel.getKompanije().get(jTableKompanija.getSelectedRow());
        JOptionPane.showMessageDialog(this, kompanija.getKompanijaID());
        PodaciKompanijaForm psf = new PodaciKompanijaForm(kompanija, this);
        
        psf.setVisible(true);
        psf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButtonImijeniKompanijuActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajKompanijuUPraksu;
    private javax.swing.JButton jButtonDodajStudentaUPraksu;
    private javax.swing.JButton jButtonImijeniKompaniju;
    private javax.swing.JButton jButtonIzmijeniStudenta;
    private javax.swing.JButton jButtonObrisiKompaniju;
    private javax.swing.JButton jButtonObrisiStudenta;
    private javax.swing.JButton jButtonPretraziStudenta;
    private javax.swing.JButton jButtonPronadjiKompaniju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableKompanija;
    private javax.swing.JTable jTableStudenti;
    private javax.swing.JTextField jTextFieldKriterijumKompanija;
    private javax.swing.JTextField jTextFieldKriterijumStudent;
    // End of variables declaration//GEN-END:variables

    public void srediStudentTabelu() {
        
        try {
            studenti = Controler.getInstance().ucitajSveStudente();
            studentModel = new StudentTableModel(studenti);
            jTableStudenti.setModel(studentModel);
            studentModel.fireTableDataChanged();
            
            
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UcitavanjeStudenataException ex) {
            JOptionPane.showMessageDialog(jMenu1, ex.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void osveziTabeluStudent() {
        studentModel.fireTableDataChanged();
    }

    public void srediKompanijaTabelu() {
        try {
            kompanije = Controler.getInstance().ucitajSveKompanije();
            kompanijaModel = new KompanijaTableModel(kompanije);
            jTableKompanija.setModel(kompanijaModel);
            kompanijaModel.fireTableDataChanged();
            
            
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UcitavanjeKompanijaException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
}
