/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controler.Controler;
import domen.AbstractObject;
import domen.Fakultet;
import domen.Student;
import exception.UcitavanjeFakultetaException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.Border;
import javax.swing.JOptionPane;

/**
 *
 * @author FILIP
 */
public class PodaciStudentForm extends javax.swing.JFrame {

    MainForm mainForm;
    String tipUnosa;
    Student studentZaIzmjenu;
    /**
     * Creates new form UnosStudentaForm
     */
    public PodaciStudentForm(MainForm mainForm) {
        this();
        this.mainForm = mainForm;
        tipUnosa = "INSERT";
    }
    
    public PodaciStudentForm() {
        initComponents();
        popuniCBFakulteti();
    }

    PodaciStudentForm(Student student, MainForm mainForm) {
        this();
        this.mainForm = mainForm;
        this.studentZaIzmjenu = student;
        jTextFieldBrIndeksa.setText(student.getBrIndeksa());
        jTextFieldImeStudenta.setText(student.getIme());
        jTextFieldPrezimeStudenta.setText(student.getPrezime());
        jTextFieldGodinaUpisa.setText(student.getGodinaUpisa());
        jComboBoxFakulteti.setSelectedItem(student.getFakultet());
        tipUnosa = "UPDATE";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxFakulteti = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldImeStudenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrezimeStudenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldGodinaUpisa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonSacuvajStudenta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBrIndeksa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unos novog studenta");

        jLabel1.setText("Odaberite fakultet:");

        jComboBoxFakulteti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFakultetiActionPerformed(evt);
            }
        });

        jLabel2.setText("Student:");

        jLabel3.setText("Ime:");

        jTextFieldImeStudenta.setToolTipText("");

        jLabel4.setText("Prezime:");

        jLabel5.setText("Godina upisa ");

        jTextFieldGodinaUpisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGodinaUpisaActionPerformed(evt);
            }
        });

        jLabel6.setText("(Unesite u formatu GGGG)");

        jButtonSacuvajStudenta.setText("Sacuvaj studenta");
        jButtonSacuvajStudenta.setToolTipText("dsadasad");
        jButtonSacuvajStudenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajStudentaActionPerformed(evt);
            }
        });

        jLabel7.setText("Broj indeksa");

        jTextFieldBrIndeksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBrIndeksaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxFakulteti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldGodinaUpisa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSacuvajStudenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextFieldPrezimeStudenta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldImeStudenta, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBrIndeksa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFakulteti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldImeStudenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPrezimeStudenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldBrIndeksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldGodinaUpisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButtonSacuvajStudenta))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGodinaUpisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGodinaUpisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGodinaUpisaActionPerformed

    private void jComboBoxFakultetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFakultetiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxFakultetiActionPerformed

    private void jButtonSacuvajStudentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajStudentaActionPerformed
        // TODO add your handling code here:      
        Student student = vratiStudenta();
        
        try {
            if(tipUnosa == "INSERT") {
                
                if(student != null) {
                    Controler.getInstance().unesiNovogStudenta(student);
                    JOptionPane.showMessageDialog(this, "Uspesno sacuvan student");
                    ocistiPolja();
                    mainForm.srediStudentTabelu();
                }
            } else {
                if(student != null) {
                    student.setStudentID(studentZaIzmjenu.getStudentID());
                    Controler.getInstance().azurirajStudenta(student);
                    JOptionPane.showMessageDialog(this, "Uspesno azuriran student");
                    dispose();
                    mainForm.srediStudentTabelu();
                }
            }
            
        } catch (IOException ex) {
            Logger.getLogger(PodaciStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PodaciStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(PodaciStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSacuvajStudentaActionPerformed

    private void jTextFieldBrIndeksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBrIndeksaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBrIndeksaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PodaciStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PodaciStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PodaciStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PodaciStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PodaciStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSacuvajStudenta;
    private javax.swing.JComboBox<Fakultet> jComboBoxFakulteti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldBrIndeksa;
    private javax.swing.JTextField jTextFieldGodinaUpisa;
    private javax.swing.JTextField jTextFieldImeStudenta;
    private javax.swing.JTextField jTextFieldPrezimeStudenta;
    // End of variables declaration//GEN-END:variables

    private void popuniCBFakulteti() {
        List<AbstractObject> fakulteti = new ArrayList<>();
        try {
            fakulteti = Controler.getInstance().ucitajSveFakultete();
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju fakulteta!");
            Logger.getLogger(PodaciStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PodaciStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UcitavanjeFakultetaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            this.dispose();
            Logger.getLogger(PodaciStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (AbstractObject fakultet : fakulteti) {
            jComboBoxFakulteti.addItem((Fakultet) fakultet);
        }
    }

    private Student vratiStudenta() {
        String ime = jTextFieldImeStudenta.getText().trim();
        String prezime = jTextFieldPrezimeStudenta.getText().trim();
        String godinaUpisa = jTextFieldGodinaUpisa.getText().trim();
        String brIndeksa = jTextFieldBrIndeksa.getText().trim();
        Fakultet fakultet = (Fakultet) jComboBoxFakulteti.getSelectedItem();
        
        return validirajIVrati(ime, prezime, brIndeksa,godinaUpisa, fakultet);
    }

    private Student validirajIVrati(String ime, String prezime, String brIndeksa, String godinaUpisa, Fakultet fakultet) {
        Student student = null;

        if(ime.isEmpty()){
            JOptionPane.showMessageDialog(this, "Unesite ime!");
        } else if(prezime.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite prezime!");
        } else if(godinaUpisa.isEmpty() || godinaUpisa.length() > 4) {
            JOptionPane.showMessageDialog(this, "Unesite godinu upisa u ispravnom formatu!");
        } else if(fakultet == null) {
            JOptionPane.showMessageDialog(this, "Odaberite fakultet!");
        } else if(brIndeksa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite broj indeksa!");
        } else {
            student = new Student(0, ime, prezime, brIndeksa, godinaUpisa, false, fakultet);            
        }
        
        return student;
    }

    private void ocistiPolja() {
        jTextFieldBrIndeksa.setText("");
        jTextFieldGodinaUpisa.setText("");
        jTextFieldImeStudenta.setText("");
        jTextFieldPrezimeStudenta.setText("");
    }
}
