/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controler.Controler;
import domen.AbstractObject;
import domen.Bransa;
import domen.Kompanija;
import exception.UcitavanjeBransiException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author FILIP
 */
public class PodaciKompanijaForm extends javax.swing.JFrame {

    DefaultListModel lm;
    MainForm mainForm;
    private Kompanija kompanijaZaIzmjenu;
    String tipUnosa;
    /**
     * Creates new form PodaciKompanijaForm
     */
    
    public PodaciKompanijaForm(MainForm mainForm) {
        this();
        this.mainForm = mainForm;
        tipUnosa = "INSERT";
    }
    public PodaciKompanijaForm() {
        initComponents();
        popuniCBBranse();
        lm = new DefaultListModel();
        
    }
    

    PodaciKompanijaForm(Kompanija kompanija, MainForm mainForm) {
        this();
        this.mainForm = mainForm;
        this.kompanijaZaIzmjenu = kompanija;
        jTextFieldRegBr.setText(kompanija.getRegBr());
        jTextFieldSifraDjelatnosti.setText(kompanija.getSifraDelatnosti());
        jTextFieldPoslovnoIme.setText(kompanija.getPoslovnoIme());
        jTextFieldKontakt.setText(kompanija.getKontakt());
        tipUnosa = "UPDATE";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxBransa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRegBr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSifraDjelatnosti = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPoslovnoIme = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldKontakt = new javax.swing.JTextField();
        jButtonSacuvajKompaniju = new javax.swing.JButton();
        jButtonDodajBransu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBranse = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unos kompanije");

        jLabel1.setText("Dodaj bransu:");

        jLabel2.setText("Registarski broj");

        jLabel3.setText("Sifra djelatnosti");

        jLabel4.setText("Poslovno ime:");

        jLabel5.setText("Kontakt:");

        jButtonSacuvajKompaniju.setText("Sacuvaj kompaniju");
        jButtonSacuvajKompaniju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajKompanijuActionPerformed(evt);
            }
        });

        jButtonDodajBransu.setText("Dodaj");
        jButtonDodajBransu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajBransuActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListBranse);

        jButton1.setText("Obrisi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldRegBr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldSifraDjelatnosti, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPoslovnoIme)
                            .addComponent(jTextFieldKontakt)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(jComboBoxBransa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDodajBransu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvajKompaniju, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldRegBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSifraDjelatnosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPoslovnoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBransa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDodajBransu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvajKompaniju))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajKompanijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajKompanijuActionPerformed
        // TODO add your handling code here:
        Kompanija kompanija = vratiKompaniju();
        
       
        if(kompanija != null) {
            try {
                if(tipUnosa == "INSERT") {
                    Controler.getInstance().unesiNovuKompaniju(kompanija);
                    JOptionPane.showMessageDialog(this, "Uspesno sacuvana kompanija");
                    ocistiPolja();
                    mainForm.srediKompanijaTabelu();
                } else {
                    if(kompanija != null) {
                    kompanija.setKompanijaID(kompanijaZaIzmjenu.getKompanijaID());
                    Controler.getInstance().azurirajKompaniju(kompanija);
                    JOptionPane.showMessageDialog(this, "Uspesno azurirana kompanija");
                    dispose();
                    mainForm.srediKompanijaTabelu();
                }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PodaciKompanijaForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greska pri unosu kompanije!");
                Logger.getLogger(PodaciKompanijaForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButtonSacuvajKompanijuActionPerformed

    private void jButtonDodajBransuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajBransuActionPerformed
        // TODO add your handling code here:
        
        Bransa bransa = (Bransa) jComboBoxBransa.getSelectedItem();
        if(bransa == null) {
            JOptionPane.showMessageDialog(this, "Odaberite bransu!");
            return;
        }
        if(lm.contains(bransa)) {
            JOptionPane.showMessageDialog(this, "Bransa je vec unijeta!");
            return;
        }
        lm.addElement(bransa);
        jListBranse.setModel(lm);
    }//GEN-LAST:event_jButtonDodajBransuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            lm.remove(jListBranse.getSelectedIndex());
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PodaciKompanijaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PodaciKompanijaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PodaciKompanijaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PodaciKompanijaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PodaciKompanijaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDodajBransu;
    private javax.swing.JButton jButtonSacuvajKompaniju;
    private javax.swing.JComboBox<Bransa> jComboBoxBransa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<Bransa> jListBranse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldKontakt;
    private javax.swing.JTextField jTextFieldPoslovnoIme;
    private javax.swing.JTextField jTextFieldRegBr;
    private javax.swing.JTextField jTextFieldSifraDjelatnosti;
    // End of variables declaration//GEN-END:variables

    private void popuniCBBranse() {
        List<AbstractObject> branse = new ArrayList<>();
        
        try {
            branse = Controler.getInstance().ucitajSveBranse();
            
        } catch (IOException ex) {
            Logger.getLogger(PodaciKompanijaForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PodaciKompanijaForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UcitavanjeBransiException ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju bransi!");
            Logger.getLogger(PodaciKompanijaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (AbstractObject o : branse) {
            jComboBoxBransa.addItem((Bransa)o);
        }
    }

    private void ocistiPolja() {
        jTextFieldRegBr.setText("");
        jTextFieldSifraDjelatnosti.setText("");
        jTextFieldPoslovnoIme.setText("");
        jTextFieldKontakt.setText("");
        lm.removeAllElements();
    }

    private Kompanija vratiKompaniju() {
        String regBr = jTextFieldRegBr.getText();
        String sifraDjelatnosti = jTextFieldSifraDjelatnosti.getText();
        String poslovnoIme = jTextFieldPoslovnoIme.getText();
        String kontakt = jTextFieldKontakt.getText();
        List<Bransa> branse = new ArrayList<>();
        for (int i = 0; i < lm.size(); i++) {
            branse.add((Bransa) lm.get(i));
            
        }
        
        return validirajIVrati(regBr, sifraDjelatnosti, poslovnoIme, kontakt, branse);
    
    }

    private Kompanija validirajIVrati(String regBr, String sifraDjelatnosti, String poslovnoIme, String kontakt, List<Bransa> branse) {
        Kompanija kompanija = null;
        if(regBr.isEmpty()){
            JOptionPane.showMessageDialog(this, "Unesite registarski broj!");
        } else if(sifraDjelatnosti.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite sifru djelatnosti!");
        } else if(poslovnoIme.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite poslovno ime!");
        } else if(kontakt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite kontakt!");
        } else if((branse == null || branse.isEmpty()) && !tipUnosa.equals("UPDATE")) {
            JOptionPane.showMessageDialog(this, "Dodajte branse!");
        } else {
            kompanija = new Kompanija(0, regBr, sifraDjelatnosti, poslovnoIme, kontakt, branse);
        }
        return kompanija;
    }
}
